version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REPOSITORY_URL:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPOSITORY_URL:$IMAGE_TAG
      - printf "[{\"name\":\"flask-app\",\"imageUri\":\"%s\"}]" $ECR_REPOSITORY_URL:$IMAGE_TAG > imagedefinitions.json
      - pwd; ls -al; cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json